[satellites.ETROC2Classic]

[satellites.ETROC2Classic.One]
fast_command_memo = "Start Triggerbit"
polarity = 0x4023
active_channel = 0xf
timestamp = 0x10
# LSB needs to be 10000 for LED page set for all channels. or 00000/00100/01000/01100
triggerbit_delay = 0x4de4
counter_duration = 0x1400

[satellites.ETROC2Receiver]

[satellites.ETROC2Receiver.One]
output_path = "/home/daq/ETROC2/ETROC-Data/DESYMar2025/beam_test"
translate = 1
compressed_binary = 0
skip_fillers = 1