[satellites.ETROC2Classic]

[satellites.ETROC2Classic.One]
fast_command_memo = "Start QInj repeatedQInj=64 L1A L1ARange uniform Triggerbit"
polarity = 0xC123
prescale_factor = 2048
active_channel = 0x000f
timestamp = 0x0010
fc_delays = 0b0101110001000000 # register 4
data_delays_01 = 0b0001000011001111 # register 5
data_delays_23 = 0b0000111100000101 # register 6
counter_duration = 0b0110010000000000 # register 7

[satellites.ETROC2Receiver]

[satellites.ETROC2Receiver.One]
output_path = "/home/daq/ETROC2/ETROC-Data/NW_SEU_May2025/NW"
translate = 0
compressed_binary = 1
skip_fillers = 0
