[satellites.ETROC2Classic]

[satellites.ETROC2Classic.One]
fast_command_memo = "Start QInj Triggerbit BCR"
polarity = 0x4123
active_channel = 0xf
timestamp = 0x10

triggerbit_delay = 0x8de4

[satellites.ETROC2Receiver]

[satellites.ETROC2Receiver.One]
output_path = "/home/daq/ETROC2/ETROC-Data/DESY_May2025/Pre"
translate = 1
compressed_binary = 0
skip_fillers = 1