MUX64:
    channel:
        LV_RB:
            pin: 0x00
            R1: 10
            R2: 1
            sig_name: unsed
            comment: "LV RB"
            terminal_input: False
        PTAT4:
            pin: 0x11
            R1: 2.0
            R2: 1.2
            sig_name: unsed
            comment: "PTAT4"
            terminal_input: False
        PENABLE4:
            pin: 0x12
            R1: 0.0
            R2: 1.2
            sig_name: unsed
            comment: "PEnable4"
            terminal_input: False
        PTAT5:
            pin: 0x13
            R1: 2.0
            R2: 1.2
            sig_name: unsed
            comment: "PTAT5"
            terminal_input: False
        PENABLE5:
            pin: 0x14
            R1: 0.0
            R2: 1.2
            sig_name: unsed
            comment: "PEnable5"
            terminal_input: False
        PTAT3:
            pin: 0x15
            R1: 2.0
            R2: 1.2
            sig_name: unsed
            comment: "PTAT3"
            terminal_input: False
        PTAT2:
            pin: 0x17
            R1: 2.0
            R2: 1.2
            sig_name: unsed
            comment: "PTAT2"
            terminal_input: False
        PENABLE2:
            pin: 0x18
            R1: 0.0
            R2: 1.2
            sig_name: unsed
            comment: "PEnable2"
            terminal_input: False
        PTAT1:
            pin: 0x19
            R1: 2.0
            R2: 1.2
            sig_name: unsed
            comment: "PTAT1"
            terminal_input: False
        PENABLE1:
            pin: 0x1A
            R1: 0.0
            R2: 1.2
            sig_name: unsed
            comment: "PEnable1"
            terminal_input: False
        GROUND:
            pin: 0x3F
            R1: 0.0
            R2: 1.0
            sig_name: unsed
            comment: "Background"
            terminal_input: False


LPGBT:
    adc:
        TH1:
            pin: 0x00
            current: 1
            conv: 1
            min: 0
            max: 1.0
            flavor: small
            comment: VTRX TH1
        MUX64OUT:
            pin: 0x01
            current: 0
            conv: 1.0
            min: 1.12
            max: 1.68
            flavor: small
            comment: MUX64OUT
        LVRB:
            pin: 0x02
            current: 0
            conv: 11.0
            min: 8.0
            max: 10.0
            flavor: small
            comment: LVRB / 11.0
        2V5TX_ADC:
            pin: 0x03
            current: 0
            conv: 3.0
            min: 2.0
            max: 3.0
            flavor: small
            comment: 2V5TX * 0.33
        RSSI_ADC:
            pin: 0x04
            current: 0
            conv: 1
            min: 0
            max: 1.0
            flavor: small
            comment: RSSI
        1V2RA:
            pin: 0x05
            current: 0
            conv: 2.0
            min: 0.8
            max: 1.4
            flavor: small
            comment: 1V2RA * 0.5 (ADC5)
        2V5RX_ADC:
            pin: 0x06
            current: 0
            conv: 3.0
            min: 2.0
            max: 3.0
            flavor: small
            comment: 2V5RX * 0.33
        VTEMP_ADC:
            pin: 0x07
            current: 0
            conv: 1
            min: 0
            max: 1.0
            flavor: small
            comment: RT1
        EOM_ADC:
            pin: 0x08
            current: 0
            conv: 1
            flavor: small
            comment: EOM DAC (internal signal)
        VDDIO:
            pin: 0x09
            current: 0
            conv: 2.38
            flavor: small
            comment: VDDIO * 0.42 (internal signal)
        VDDTX:
            pin: 0x0a
            current: 0
            conv: 2.38
            flavor: small
            comment: VDDTX * 0.42 (internal signal)
        VDDRX:
            pin: 0x0b
            current: 0
            conv: 2.38
            flavor: small
            comment: VDDRX * 0.42 (internal signal)
        VDD:
            pin: 0x0c
            current: 0
            conv: 2.38
            flavor: small
            comment: VDD * 0.42 (internal signal)
        VDDA:
            pin: 0x0d
            current: 0
            conv: 2.38
            flavor: small
            comment: VDDA * 0.42 (internal signal)
        TEMP:
            pin: 0x0e
            current: 0
            conv: 1
            flavor: small
            comment: Temperature sensor (internal signal)
        VREF:
            pin: 0x0f
            current: 0
            conv: 2.0
            flavor: small
            comment: VREF/2 (internal signal)
    gpio:
        MUXCNT5:
            pin: 0x00
            default: 1
            direction: out
            flavor: small
            comment: MUXCNT5
        MUXCNT4:
            pin: 0x01
            default: 1
            direction: out
            flavor: small
            comment: MUXCNT4
        MUXCNT6:
            pin: 0x02
            default: 1
            direction: out
            flavor: small
            comment: MUXCNT6
        MUXCNT3:
            pin: 0x03
            default: 1
            direction: out
            flavor: small
            comment: MUXCNT3
        MUXCNT1:
            pin: 0x04
            default: 1
            direction: out
            flavor: small
            comment: MUXCNT1
        MUXCNT2:
            pin: 0x05
            default: 1
            direction: out
            flavor: small
            comment: MUXCNT2
        RESET1:
            pin: 0x08
            default: 1
            direction: out
            flavor: small
            comment: Reset 
        LD_RSTN:
            pin: 0x0A
            default: 1
            direction: out
            flavor: small
            comment: LED
        RESET2:
            pin: 0x0B
            default: 1
            direction: out
            flavor: small
            comment: Reset
        LD_DIS:
            pin: 0x0D
            default: 0
            direction: out
            flavor: small
            comment: LD_DIS
        MODULE_SELECT0:
            pin: 0x0E
            default: 0
            direction: out
            flavor: small
            comment: MODULE_SELECT0
LPGBT2:
    adc:
    gpio:
        PENABLE1:
            pin: 0x00
            default: 0
            direction: out
            flavor: small
            comment: Enable power on inductor 1
        PENABLE5:
            pin: 0x01
            default: 0
            direction: out
            flavor: small
            comment: Enable power on inductor 5
        PENABLE2:
            pin: 0x02
            default: 0
            direction: out
            flavor: small
            comment: Enable power on inductor 2
        PENABLE4:
            pin: 0x03
            default: 0
            direction: out
            flavor: small
            comment: Enable power on inductor 4
        MODULE_SELECT2:
            pin: 0x05
            default: 0
            direction: out
            flavor: small
            comment: MODULE_SELECT2
        LED_0:
            pin: 0x0B
            default: 1
            direction: out
            flavor: small
            comment: LED 1 on schematic, GPIO config LED
        LED_1:
            pin: 0x0C
            default: 0
            direction: out
            flavor: small
            comment: LED 2 on schematic
        MODULE_SELECT1:
            pin: 0x0E
            default: 0
            direction: out
            flavor: small
            comment: MODULE_SELECT1
        VREF_ENABLE:
            pin: 0x0F
            default: 0
            direction: out
            flavor: small
            comment: VREF_ENABLE

inversions:
   clocks: []
   downlink: []
   uplink: []
   trigger: []
